apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: example-job-2
spec:
  completions: 8
  template:
    metadata:
      name: example-job-2a
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl"]
        args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
      # Do not restart containers after they exit
      restartPolicy: Never
