runtime: custom
env: flex
service: graph
env_variables:
  KAGGLE_USERNAME: garrettw3
  KAGGLE_KEY: 2b3221c5b0a0a2100ca6535618e4b8ca
network:
  name: projects/network-prd-3aa9/global/networks/vpc-prd
  subnetwork_name: app-us-c1
