---
- name: "Sample Playbook"
  hosts: localhost
  tasks:
    - apt: 
          name: python3-venv
      become: true    
    - pip:
          virtualenv: /tmp/py3
          virtualenv_command: /usr/bin/python3 -m venv
          name: mysql-connector-python 

    - name: Create a new database with name 'bobdata'
      mysql_db:
          name: bobdata
          state: present


