runtime: custom
env: flex
skip_files:
- ^(.*/)?\.bak$
- ^(.*/)?\.swp$

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 15
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

network:
  name: projects/[NETWORK_PROJECT_ID]/global/networks/[VPC_NAME]
  subnetwork_name: [SUBNETWORK_NAME]
